export const PASTEL_COLORS = [
  // 파스텔 12개
  { hex: "#FFB3BA", name: "파스텔 핑크" },
  { hex: "#FFDFBA", name: "파스텔 피치" },
  { hex: "#FFFFBA", name: "파스텔 옐로우" },
  { hex: "#BAFFC9", name: "파스텔 민트" },
  { hex: "#BAE1FF", name: "파스텔 하늘" },
  { hex: "#D4BAFF", name: "파스텔 라벤더" },
  { hex: "#FFD4BA", name: "파스텔 살구" },
  { hex: "#FFBAD4", name: "파스텔 로즈" },
  { hex: "#F0FFBA", name: "파스텔 라임" },
  { hex: "#FFE4BA", name: "파스텔 버터" },
  { hex: "#BAD4FF", name: "파스텔 연파랑" },
  { hex: "#C9FFD4", name: "파스텔 연두" },
  // 진한 12개 (파스텔과 같은 색조 계열)
  { hex: "#FF6B7A", name: "딥 핑크" },
  { hex: "#FF9A5C", name: "딥 피치" },
  { hex: "#FFD93D", name: "딥 옐로우" },
  { hex: "#6BCB77", name: "딥 민트" },
  { hex: "#4DA6FF", name: "딥 하늘" },
  { hex: "#9B77FF", name: "딥 라벤더" },
  { hex: "#FF8C5A", name: "딥 살구" },
  { hex: "#FF5C8A", name: "딥 로즈" },
  { hex: "#C8E840", name: "딥 라임" },
  { hex: "#FFC044", name: "딥 버터" },
  { hex: "#5B9BFF", name: "딥 파랑" },
  { hex: "#3DBD6B", name: "딥 연두" },
];
