// 모든 스티커 정의 - public/stickers 폴더의 이미지를 모두 포함합니다.
export interface StickerDef {
  id: string;
  emoji?: string;
  src?: string;
  label: string;
}

export const ALL_STICKERS: StickerDef[] = [
  { id: 'art', src: '/stickers/art.png', label: '미술' },
  { id: 'band', src: '/stickers/band.png', label: '밴드' },
  { id: 'bath', src: '/stickers/bath.png', label: '목욕' },
  { id: 'bear_1', src: '/stickers/bear_1.png', label: '곰' },
  { id: 'bear_2', src: '/stickers/bear_2.png', label: '아기곰' },
  { id: 'book_1', src: '/stickers/book_1.png', label: '독서' },
  { id: 'camera', src: '/stickers/camera.png', label: '카메라' },
  { id: 'candle', src: '/stickers/candle.png', label: '촛불' },
  { id: 'candy', src: '/stickers/candy.png', label: '사탕' },
  { id: 'car', src: '/stickers/car.png', label: '자동차' },
  { id: 'check', src: '/stickers/check.png', label: '체크' },
  { id: 'clock', src: '/stickers/clock.png', label: '시계' },
  { id: 'cloth', src: '/stickers/cloth.png', label: '옷' },
  { id: 'coffee', src: '/stickers/coffee.png', label: '커피' },
  { id: 'diaper', src: '/stickers/diaper.png', label: '기저귀' },
  { id: 'duck', src: '/stickers/duck.png', label: '오리' },
  { id: 'etc', src: '/stickers/etc.png', label: '기타' },
  { id: 'etc_2', src: '/stickers/etc_2.png', label: '기타2' },
  { id: 'etc_3', src: '/stickers/etc_3.png', label: '기타3' },
  { id: 'etc_4', src: '/stickers/etc_4.png', label: '기타4' },
  { id: 'flower_1', src: '/stickers/flower_1.png', label: '꽃1' },
  { id: 'flower_2', src: '/stickers/flower_2.png', label: '꽃2' },
  { id: 'flower_3', src: '/stickers/flower_3.png', label: '꽃3' },
  { id: 'headset', src: '/stickers/headset.png', label: '헤드셋' },
  { id: 'heart', src: '/stickers/heart.png', label: '하트' },
  { id: 'heart_2', src: '/stickers/heart_2.png', label: '하트2' },
  { id: 'icecream', src: '/stickers/icecream.png', label: '아이스크림' },
  { id: 'lamp', src: '/stickers/lamp.png', label: '스탠드' },
  { id: 'meal', src: '/stickers/meal.png', label: '식사' },
  { id: 'meal_2', src: '/stickers/meal_2.png', label: '이유식' },
  { id: 'milk', src: '/stickers/milk.png', label: '우유' },
  { id: 'milk_2', src: '/stickers/milk_2.png', label: '수유' },
  { id: 'mom', src: '/stickers/mom.png', label: '엄마' },
  { id: 'moon', src: '/stickers/moon.png', label: '달' },
  { id: 'moon_2', src: '/stickers/moon_2.png', label: '밤' },
  { id: 'moon_3', src: '/stickers/moon_3.png', label: '초승달' },
  { id: 'movie', src: '/stickers/movie.png', label: '영화' },
  { id: 'music', src: '/stickers/music.png', label: '음악' },
  { id: 'notbook', src: '/stickers/notbook.png', label: '노트북' },
  { id: 'pencil', src: '/stickers/pencil.png', label: '연필' },
  { id: 'popcorn', src: '/stickers/popcorn.png', label: '팝콘' },
  { id: 'rainbow', src: '/stickers/rainbow.png', label: '무지개' },
  { id: 'ribbon', src: '/stickers/ribbon.png', label: '리본' },
  { id: 'run', src: '/stickers/run.png', label: '운동' },
  { id: 'sleep', src: '/stickers/sleep.png', label: '수면' },
  { id: 'sleep_clock', src: '/stickers/sleep_clock.png', label: '낮잠' },
  { id: 'spark', src: '/stickers/spark.png', label: '스파클' },
  { id: 'sprout', src: '/stickers/sprout.png', label: '새싹' },
  { id: 'star', src: '/stickers/star.png', label: '별' },
  { id: 'stroller', src: '/stickers/stroller.png', label: '유모차' },
  { id: 'study', src: '/stickers/study.png', label: '공부' },
  { id: 'sun', src: '/stickers/sun.png', label: '해' },
  { id: 'suncream', src: '/stickers/suncream.png', label: '선크림' },
  { id: 'toothbrush', src: '/stickers/toothbrush.png', label: '양치' },
  { id: 'tree', src: '/stickers/tree.png', label: '나무' },
  { id: 'tv', src: '/stickers/tv.png', label: 'TV' },
];
